### ISSUE TITLE
Add `--kifu` flag

### ISSUE THREAD

**Issue by julianandrews** [julianandrews/sgf-render#15]
I should add a flag for generating kifu. When using `--kifu`:

- `--move-numbers` will be enabled
- `--node` will default to `last`
- Captured stones will still be displayed on the board.
- Annotations will be added to the bottom showing repeated stones
  - Each repeated mode will get its own entry referencing the first stone played.

See issues #6 and #9 for more context.

**Comment by julianandrews** [comment]
With v2.3.0 we've got `--kifu`.

@tdnetdog - I think this should address your issues raised in #6!

**Comment by tdnetdog** [comment]
exactly, thanks
