### ISSUE TITLE
About SGF-format 

### ISSUE THREAD

**Issue by roykoand** [julianandrews/sgf-render#20]
Hello, Julian. 
Thank you for this great and helpful project.
But I have one issue with SGF-formats. For example, I use the game in SGF-format from https://github.com/featurecat/go-dataset.
Link to file example in SGF-format: https://drive.google.com/file/d/1a5a7kD3bQFIR-_CY5HBbfeZzH6WDVddG/view?usp=sharing
Then, I run ```path/to/repo/target/release/sgf-render path/to/file/1486988818019999291.sgf -o test.png```.
And this command generates an empty board correct size (board without stones, but with correct dimension). 
I also tried SGF-format from https://online-go.com/, and it does not work for me also.
Lint to file example in SGF-format: https://drive.google.com/file/d/1OH5L7aqDV3Bf1gzeWeKTPnEZ0isqmsNb/view?usp=sharing
I guess it's because SGF-format in this file contains chat messages and other metadata from the site, I tried to clean it, but still does not work (but it was like monkey cleaning :) ).
Your ```sgf-render/tests/data/prob45/input.sgf``` work clearly for me.
Again thank you for your work and apologize if I haven't figured out your project clearly and this issue is trash.

If it will be useful:
```cargo 1.46.0```

**Comment by julianandrews** [comment]
Hi!

By default `sgf-render` shows the first node in a game (which is often empty). You can show the 10th node by using the `-n 10` and the last node by using `-n last` (the README has more details on node selection if you need more control than that).

So taking your command, it would look like:

```
path/to/repo/target/release/sgf-render path/to/file/1486988818019999291.sgf -n last -o test.png
```

I should probably add a brief write-up to the help to make this clear. I think it's confusing for a lot of people.

**Comment by roykoand** [comment]
Yeah, I missed it in the README, everything works. Thank you very much for open-sourcing this project :)
