### ISSUE TITLE
Keep markup on empty intersections when --move-numbers is enabled

### ISSUE THREAD

**Issue by abaisero** [julianandrews/sgf-render#23]
Hi!  Finally I found a simple working and modern project which did what I needed.  Thanks for setting this up.

I'm planning to use this to create some notes on various endgame situations, and one very common usecase for me would be to show both the move numbers (to show possible endgame sequences), but also keep the markup which is used to highlight the respective point differences.  I assume the reason why move numbers disables markup is because you couldn't show both when they're both located on a stone (or you might, but it would be confusing anyway).  But in my use-case, the markup would only be in the empty intersections anyway.  Would it be possible to include this feature?  Removing the markup only from the numbered moves would be sufficient for my use case.

Thanks again!

**Comment by julianandrews** [comment]
This seems like a sensible change.

On reflection, I think disabling markup when using `--move-numbers` was a mistake - users can always explicitly disable markup if they need to, and most SGFs that you're likely to render with `--move-numbers` don't have markup anyway. If you do have markup in your SGF the behavior should be an explicit choice.

I'll also add a `--no-markup` flag that will be equivalent to `--no-marks --no-circles --no-squares --no-selected --no-dimmed --no-labels --no-lines --no-arrows` which should make getting the old behavior easy with `--move-numbers --no-markup`.
