### ISSUE TITLE
Allow Export to png via stdout

### ISSUE THREAD

**Issue by purxiz** [julianandrews/sgf-render#26]
Right now, specifying no output means the program outputs an svg to stdout. I'd like to have a -format or -f option with options png and/or sgf. Should have a pull request ready soon.

**Comment by julianandrews** [comment]
Just to check, is the use case that you want to be able to output a png directly to stdout? Or output either a png or svg to a filename with a different extension?

In any case, as long as the default behavior stays the same, and the option to compile without PNG support remains, this sounds like a good change to me!

**Comment by purxiz** [comment]
I want to be able to export a png to stdout. I submitted a basic PR that kinda does what I want, but isn't ready to be merged. I'll try to make it better over the next few days.

**Comment by purxiz** [comment]
If you could give me some guidance in making sure it can compile without png support, I'm all ears

**Comment by julianandrews** [comment]
Sorry for dropping the ball on communicating on this one. I did finally get around to doing the changes, so starting with v2.6.0 it should be possible to output PNGs to stdout.

**Comment by purxiz** [comment]
Thanks! I also dropped the ball, glad to hear it's ready
