### ISSUE TITLE
IGS Incompatibility

### ISSUE THREAD

**Issue by PelleasGo** [julianandrews/sgf-render#3]
Apologies if this is the wrong place to leave this. But when you try to render from a SGF gotten from IGS/PandaNet, you receive the error: "Failed to load SGF node: Error tokenizing: Unexpected end of property". It seems that the only issue is with the copyright section from the IGS/PandaNet SGF, as when I remove that line from the SGF, it renders.

**Comment by julianandrews** [comment]
This is a fine place to open the issue! Would you be willing to share an SGF that fails? I suspect I know what the issue is, but it would be good to be able to confirm I've fixed the real bug when I do it!

**Comment by julianandrews** [comment]
Alternatively - if you could just confirm that the issues comes from a block that looks something like:

```
CoPyright[
Copyright (c) PANDANET Inc. 2014
Permission to reproduce this game is given, provided proper credit is given.
No warrantee, implied or explicit, is understood.
Use of this game is an understanding and agreement of this notice.
]
```

I can take it from there!

**Comment by PelleasGo** [comment]
Yes, that's the block!
