### ISSUE TITLE
PNG output failing to render arrows in repeated stones section

### ISSUE THREAD

**Issue by julianandrews** [julianandrews/sgf-render#33]
When rendering to PNG the arrows aren't getting rendered.

![output](https://github.com/julianandrews/sgf-render/assets/607449/565a11a4-1ba8-4c59-96a7-7bc3748c3019).

**Comment by julianandrews** [comment]
It looks as if the issue here is that the arrow glyph "→" doesn't exist in the Roboto Font I'm using. Most SVG renderers will have access to full system fonts and will be able to find the glyph from another font to render, but for PNG rendering this fails. I need to either use a different glyph, or include a font with the glyph I want.

**Comment by julianandrews** [comment]
This should be fixed in the latest release.

**Comment by AprilInParis** [comment]
![4](https://github.com/julianandrews/sgf-render/assets/154599603/dc56ab8e-5331-4d79-9823-1aa6ff169d80)
![4_a](https://github.com/julianandrews/sgf-render/assets/154599603/4422b291-3bf4-4046-ac3e-d8f1f0ceee40)

Hi,

Thanks again for fixing those issues in v2.4.3

Noticed in v2.4.4 --kifu mode the new font is a tiny bit too big. The numbers in the stones are right on the edge.
Also the annotation numbers in the box, there is no clear space between them, they run into each other. 
v2.4.3 looked a perfect font size to me.

Hope I don't come across as being too nit picky, Neil

**Comment by julianandrews** [comment]
Not too nit picky at all! It's really helpful for getting this all right. I've been a little unhappy with how tightly I packed the numbers already. I think it's a good time to reduce the number of columns I try to render.

**Comment by julianandrews** [comment]
I've tweaked the font parameters. Should be a lot more readable now!
