### ISSUE TITLE
There's no convenient way to show the last move.

### ISSUE THREAD

**Issue by tdnetdog** [julianandrews/sgf-render#4]
[01.sgf.zip](https://github.com/julianandrews/sgf-render/files/6966728/01.sgf.zip)

mac bin v1.3.3
not show moves (this case `B[br]` in attached sgf)

`sgf-render 01.sgf -r am-ls --style minimalist -o a.svg --no-board-labels`
`sgf-render 01.sgf -r am-ls --style minimalist -o a.svg --no-board-labels --move-numbers`

neither works

![a](https://user-images.githubusercontent.com/1937229/128991964-3467ecb1-e6d6-4a0e-80f7-8fdcc68004e1.png)

**Comment by julianandrews** [comment]
By default `sgf-render` shows the content of the root node. If you want to show the contents of a later node, use the `-n` flag. In this case it would be something like:

```
sgf-render 01.sgf -r am-ls --style minimalist -o a.svg --no-board-labels -n 2
```

To show the content of the second node.

**Comment by tdnetdog** [comment]
thanks for reply, tried and it works, and even better with --move-numbers

however is there a way to show move to the end ? We usually don't know how many moves are there in the sgf after all, and a "MAX" enough move number will give error message

**Comment by julianandrews** [comment]
There isn't a way to do that (other than counting moves). I should definitely add that!

What do you think of something like:

```
sgf-render 01.sgf -r am-ls --style minimalist -o a.svg --no-board-labels -n last
```

**Comment by julianandrews** [comment]
Ok! You should be able to use `--node-num last` or `-n last` to render the last node (going down the first variation) in an SGF.

I want to add support for rendering other variations too, but I need to take some time to think through what the command line argument for that will look like.
