### ISSUE TITLE
SGF Variation displays in Sabaki correctly, but fails to export

### ISSUE THREAD

**Issue by vabue** [julianandrews/sgf-render#42]
SGF variation 2 is correctly displayed in Sabaki, but generates error during export:
```
sgf-render-macos % sgf-render query prob0005.sgf                                            
Game #0
v0, 0-2
├── v0, 1-2
├── v1, 1-3
└── v2, 1-2
sgf-render-macos % sgf-render -s -n last -v 0 --move-numbers prob0005.sgf -o prob0005-v0.svg
sgf-render-macos % sgf-render -s -n last -v 1 --move-numbers prob0005.sgf -o prob0005-v1.svg
sgf-render-macos % sgf-render -s -n last -v 2 --move-numbers prob0005.sgf -o prob0005-v2.svg
Failed to generate goban: Invalid move
sgf-render-macos % 

```

<img width="889" alt="image" src="https://github.com/user-attachments/assets/05f1c85c-d62d-46af-b21c-9ddd55d0063a">

Used SGF and export results:
[prob005.zip](https://github.com/user-attachments/files/17016858/prob005.zip)

**Comment by julianandrews** [comment]
Definitely looks like a bug - I'm able to reproduce it. I'll take a look soon.

**Comment by julianandrews** [comment]
This turned out to be a super easy fix.

The issue was that the SGF file had us placing a stone over top of an existing stone, and I had a check in place to prevent that. But the SGF spec explicitly allows this sort of repeated play, so I've just removed the check, and added a test!

Fix pushed, and new release coming shortly.

**Comment by julianandrews** [comment]
Ohh, and thanks for reporting the bug!

The SGF specification is fairly detailed, and I've done my best to implement it faithfully, but there are a lot of edge cases I'm not likely to ever run into, and it's really helpful when people find them for me!

**Comment by vabue** [comment]
Thanks Julian! Works like a miracle.
